//
//  ViewController.swift
//  Super-Oblique-Strategies-Starter
//
//  Created by jeazous on 7/8/21.
//

import UIKit

class ViewController: UIViewController {
    
    
    //TODO: 1. Connect IBOutlets to Storyboard, Hint: 1 for message label, 1 for generate message button, and 1 for the background view
    
    
    //TODO: 2. Create an instance of the ObliqueMessages model


    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
        
        //TODO: 6. Create a constant stores a random number generated by the method/func generateRandomNumer()
   
        //TODO: 7. Create method updates the user interface according to the message that is to be displayed

    
        //TODO: 8. Put a radius in our card view

        //TODO: 9. Do more configuration on our generate message button (border width, border color, and corner radius)
       
    
    }

    //TODO: 3. Create IBAction function for when the generate message button is clicked and call it "generateButtonClicked"
    

    //TODO: 4.Create function for generating a random number taking in account the total number of messages we have on our Oblique Messages data model and call it "generateRandomNumber"
  
    
    
    
    //TODO: 5. Creata function that Updates the message label according to the message to be displayed and call it "updateUI"
    

    
}

